name: blog
dependencies:
- openssl=1.0.2h=0
- pip=8.1.1=py35_1
- python=3.5.1=0
- readline=6.2=2
- setuptools=21.2.1=py35_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - beautifulsoup4==4.4.1
  - blinker==1.4
  - bs4==0.0.1
  - decorator==4.0.9
  - docutils==0.12
  - entrypoints==0.2.2
  - feedgenerator==1.8
  - ipykernel==4.3.1
  - ipython==4.2.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.1.5
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - markdown==2.6.6
  - markupsafe==0.23
  - mistune==0.7.2
  - nbconvert==4.2.0
  - nbformat==4.0.1
  - notebook==4.2.0
  - pelican==3.6.3
  - pexpect==4.1.0
  - pickleshare==0.7.2
  - ptyprocess==0.5.1
  - pyenchant==1.6.6
  - pygments==2.1.3
  - pyqt5==5.6
  - python-dateutil==2.5.3
  - pytz==2016.4
  - pyzmq==15.2.0
  - qtconsole==4.2.1
  - simplegeneric==0.8.1
  - sip==4.18
  - six==1.10.0
  - terminado==0.6
  - tornado==4.3
  - traitlets==4.2.1
  - unidecode==0.4.19
  - widgetsnbextension==1.2.3

